services:

  jupyter:
    image: quay.io/jupyter/datascience-notebook:python-3.11
    container_name: jupyter
    hostname: jupyter
    working_dir: /app
    ports:
    - 8888:8888
    volumes:
    - .:/app
    networks:
    - techchallenge-network

  api:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    container_name: api
    hostname: api
    working_dir: /app
    command: poetry run python -m uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    restart: always
    ports:
    - 8001:8001
    volumes:
    - .:/app
    networks:
    - techchallenge-network

volumes:
  home:

networks:
  techchallenge-network:
