services:
  jupyter:
    image: quay.io/jupyter/datascience-notebook:python-3.11
    container_name: jupyter
    hostname: jupyter
    working_dir: /app
    ports:
    - 8888:8888
    volumes:
    - .:/app
    networks:
    - techchallenge-network

  api:
    container_name: api
    hostname: api
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: .
    working_dir: /app
    user: vscode
    command: poetry run python -m uvicorn src.main:app --host '0.0.0.0' --port 8000 --reload
    volumes:
    - .:/app
    ports:
    - 8001:8000
    networks:
    - techchallenge-network

volumes:
  home:

networks:
  techchallenge-network:
