services:
  jupyter:
    image: quay.io/jupyter/datascience-notebook:python-3.11
    container_name: jupyter
    hostname: jupyter
    working_dir: /app
    env_file: .env
    ports:
    - 8888:8888
    volumes:
    - .:/app
    networks:
    - techchallenge-network

  api:
    container_name: api
    hostname: api
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: .
    working_dir: /app
    command: python -m uvicorn src.main:app --host $API_HOST --port $API_PORT --reload
    volumes:
    - .:/app
    ports:
    - $API_PORT:$API_PORT
    networks:
    - techchallenge-network

volumes:
  home:

networks:
  techchallenge-network:
